// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExWvphgevPCFUfoRVR-v9M3b_m4_BJlc',
    appId: '1:55291164735:web:ea79acdef36a4d8af2608a',
    messagingSenderId: '55291164735',
    projectId: 'quiz-app-dc1a7',
    authDomain: 'quiz-app-dc1a7.firebaseapp.com',
    storageBucket: 'quiz-app-dc1a7.appspot.com',
    measurementId: 'G-DN0TEX2G0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyPmGHeOBzYjl-Xkyvl7qWxWDw9p_w-U',
    appId: '1:55291164735:android:a3acd828e3fee475f2608a',
    messagingSenderId: '55291164735',
    projectId: 'quiz-app-dc1a7',
    storageBucket: 'quiz-app-dc1a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHnL3eJNcDyWm3-Y1Fjude7okwWPF6W5E',
    appId: '1:55291164735:ios:0a742b7ca7e20961f2608a',
    messagingSenderId: '55291164735',
    projectId: 'quiz-app-dc1a7',
    storageBucket: 'quiz-app-dc1a7.appspot.com',
    iosClientId: '55291164735-d9r9vgibtg5vbjbduipf030r0gat44pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHnL3eJNcDyWm3-Y1Fjude7okwWPF6W5E',
    appId: '1:55291164735:ios:0a742b7ca7e20961f2608a',
    messagingSenderId: '55291164735',
    projectId: 'quiz-app-dc1a7',
    storageBucket: 'quiz-app-dc1a7.appspot.com',
    iosClientId: '55291164735-d9r9vgibtg5vbjbduipf030r0gat44pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
